name: education
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_localization: ^0.2.0
  flutter_riverpod: ^2.5.1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  golden_toolkit: ^0.15.0
  http: ^1.2.1
  intl: ^0.19.0
  intl_translation: ^0.20.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  provider: ^6.1.2
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.3
  cached_network_image: ^3.1.0
  flutter_localizations:
    sdk: flutter
  flutter_gen: ^5.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  mockingjay: ^0.5.0
  http_mock_adapter: ^0.6.1
  mockito: ^5.1.0
  network_image_mock: ^2.0.1
  intl_utils: ^2.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - lib/l10n/
  fonts:
    - family: Coves
      fonts:
        - asset: assets/fonts/bold.otf
          weight: 700
        - asset: assets/fonts/light.otf
          weight: 400
  generate: true 
